### ISSUE TITLE
Update Payment Customization sample app with `presentment_currency_rate`

### ISSUE THREAD

**Issue by marlonmarcello** [Shopify/function-examples#114]
At the moment the Payment Customization sample app has a hardcoded `presentment_currency_rate` because that isn't available through the API.

We need to [update](https://github.com/Shopify/function-examples/pull/111#discussion_r992767194) that after the patterns team ship a fix for it.

**Comment by DuncanUszkay1** [comment]
We're going another direction with the sample app, so this one doesn't need to be updated. Closing this since the new sample app work is tracked elsewhere
