### ISSUE TITLE
error: could not find `Cargo.toml`

### ISSUE THREAD

**Issue by mariusa** [Shopify/function-examples#123]
Hi, on Linux, after cloning this repo:
```
$ pwd
/work/rust/function-examples/discounts/rust/product-discounts/default
$ cargo wasi build --release
error: could not find `Cargo.toml` in `/work/rust/function-examples/discounts/rust/product-discounts/default` or any parent directory
```

I did run `$ yarn expand-liquid` in `/work/rust/function-examples`

I see `Cargo.toml` used to be present, but was removed.

**Comment by nickwesselman** [comment]
`expand-liquid` should reliably create the `Cargo.toml` at this point.
