### ISSUE TITLE
Impossible to implement "Free Gift with purchase over $50"

### ISSUE THREAD

**Issue by mariusa** [Shopify/function-examples#144]
Hi,

With the current discount functions, it's impossible to implement "Free Gift with purchase over $50", a use case which was listed in the slides at Unite.

The function gets the cart input & prices as they are BEFORE other (functions) discounts are applied. But other functions could also discount some products, so an initial order total of $60 will get to $40.
We also need to know the total order amount AFTER all discounts. If it's still above $50, only then discount the free gift product.

How would this be possible?

Thanks

**Comment by kim76** [comment]
Yes, you can implement this by providing the `OrderMimimumSubtotal` which will be used by the reducer to compare to the discounted order total. https://shopify.dev/docs/api/functions/reference/order-discounts/graphql/common-objects/orderminimumsubtotal

**Comment by mariusa** [comment]
Thanks. This works, but the customer experience isn't the same as seeing the cart line item with $0 cost. They see $10 for a product they didn't asked for, and only later, in cart total (if they scroll/look), they see a -$10 discount.
