### ISSUE TITLE
Impossible to implement Volume discount with multiple tiers per product

### ISSUE THREAD

**Issue by mariusa** [Shopify/function-examples#145]
There's a huge limitation on functions (discounts) which makes this unusable in real life cases: even though a function can return a list of multiple discounts (say, one for each cart line item), Shopify will apply only one of it. We need all the discounts to be applied.

For example: Volume discounts have different tiers for different quantities. A cart line could have quantity 2 and qualify for 1st tier (10% discount), another cart line could have quantity 6 and qualify for 2nd tier (20% discount). This is impossible to handle now, as even though the function returns 2 different discounts to apply, Shopify applies only one.
Need  DiscountApplicationStrategy: ALL, not just one: https://shopify.dev/api/functions/reference/product-discounts/graphql/common-objects/discountapplicationstrategy

There are forum posts about this, but nobody at Shopify didn't even reply:
https://community.shopify.com/c/shopify-functions/shopify-functions-product-discount-api-multiple-discounts/td-p/1693369
https://community.shopify.com/c/shopify-functions/need-discountapplicationstrategy-all/td-p/1865853

**Comment by isque03** [comment]
Another +1
Ran into the same issue right away while working on implementing function discounts. Thanks for your help!

**Comment by mmarcon91** [comment]
We have the same problem

**Comment by GYMarshy** [comment]
+1 here too
