### ISSUE TITLE
Sorting delivery methods doesn't work for Local Delivery

### ISSUE THREAD

**Issue by SaeedYasin** [Shopify/function-examples#175]
Here function output is defining the sorting of the shipping methods, but that is NOT what happens on the checkout. Local delivery seems to have a mind of it's own and sometimes appears randomly as the last shipping method, which is not what the sorting function specified. Is this known behaviour or issue?

**Function Stdin:**
<img width="622" alt="Screenshot 2023-03-13 at 12 46 50 AM" src="https://user-images.githubusercontent.com/26478201/224559517-d68d5899-d66c-48c0-aa74-256ab1592f27.png">

**Function Stdout:**
<img width="907" alt="Screenshot 2023-03-13 at 12 47 05 AM" src="https://user-images.githubusercontent.com/26478201/224559553-c31b1808-ce37-4769-a197-34c2c520bf08.png">

**Checkout:**
<img width="646" alt="Screenshot 2023-03-13 at 12 47 18 AM" src="https://user-images.githubusercontent.com/26478201/224559566-cd09110f-50f6-4351-b84e-f2288cb92b1d.png">

**Store name:**
https://sylab-store.myshopify.com/

**Comment by SaeedYasin** [comment]
It seems when checkout page is rendered, then function runs 3 or 4 times. Some of those runs generate no op as shown below.
<img width="905" alt="Screenshot 2023-03-13 at 1 52 10 AM" src="https://user-images.githubusercontent.com/26478201/224562998-49878afe-ac42-473b-8b4a-07c6e6ea31f8.png">

Some of those runs only show 2 shipping methods, seems like it takes time to load Local Delivery.
<img width="913" alt="Screenshot 2023-03-13 at 1 54 40 AM" src="https://user-images.githubusercontent.com/26478201/224563136-e64e2595-d151-40cf-9f24-80f10c02199c.png">

The problem happens when a no op run happens last, then all shipping methods just appear randomly without any sorting. One would assume that even if the same function runs multiple times, it should generate same output, how is that possible that sometimes there is no output generated? There is literally no change in the function input or function code/meta field.

PS. There is only one function I've deployed which tries to sort shipping methods.

**Comment by SaeedYasin** [comment]
Found something interesting, when a no op run happens, then the metafield input is null. I didn't update metafield value, it just shows null in some of the runs.

<img width="939" alt="Screenshot 2023-03-13 at 2 01 10 AM" src="https://user-images.githubusercontent.com/26478201/224563500-ec531977-46a8-4582-8003-fcb35b07a97f.png">

**Comment by SaeedYasin** [comment]
Any solution for this?

**Comment by rameshr-shopify** [comment]
We used to have some specific sorting logic for local delivery and instore pickup before, but it shouldn't be overriding function outputs. @SaeedYasin , are you able to share the checkout token (the url) of a checkout when you encountered this issue? We'd be able to get a better understanding of what's happening if we have that info.
