### ISSUE TITLE
Used wrong api version value during initialization shopifyApp

### ISSUE THREAD

**Issue by MatrosSkin** [Shopify/function-examples#230]
https://github.com/Shopify/function-examples/blob/8b2ca3d0387a8cd40e32cb0e34246531fa183a2c/sample-apps/delivery-customizations/web/shopify.js#L21

As you can see, in config used value `"2023-04"`, but in same time `restResources` imported for version `2023-01` (look at line 4).

Also, the app, created with using of this template, can't start properly, because some of dependencies has incompatible version but it's version still matched as compatible. I was able to start the app after reinstalling of all dependencies with `npm ci` (all dependencies installed wit versions as locked in lock file).

**Comment by niveshsaharan** [comment]
I'm having this issue. If anyone can help please:

<img width="1426" alt="image" src="https://github.com/Shopify/function-examples/assets/2552126/3ddc97c2-81a9-4342-abec-85ff8b15794d">

**Comment by boyoon** [comment]
Hey @niveshsaharan were you able to figure this out? Seems like I'm running into the exact same issue.

**Comment by boyoon** [comment]
@niveshsaharan you are awesome and amazing, thank you for the solution!
