### ISSUE TITLE
Cart Transform bug: Expand operation is not carried out when all component quantities are greater than 1

### ISSUE THREAD

**Issue by ctrevorrow** [Shopify/function-examples#234]
I recognize this repo is examples of using Shopify Functions rather than the Function APIs themselves, but I'm hoping this is still a good place to report this issue.

### Discussed in https://github.com/Shopify/function-examples/discussions/226

<div type='discussions-op-text'>

<sup>Originally posted by **ctrevorrow** April 24, 2023</sup>
When all of a bundle product's component products' quantities are greater than 1, the Expand operation which the Function outputs is not carried out.  However, if one of the component products' quantities is equal to 1, the Expand operation results in the expected cart changes.

For example, this function output results in no changes in the checkout (Line #0 stays as the bundle product and DOES NOT display the components under it):
```
{
  "operations": [
    {
      "expand": {
        "cartLineId": "gid://shopify/CartLine/0",
        "expandedCartItems": [
          {
            "merchandiseId": "gid://shopify/ProductVariant/<component_variant_id_1>",
            "quantity": 3
          },
          {
            "merchandiseId": "gid://shopify/ProductVariant/<component_variant_id_2>",
            "quantity": 2
          },
          {
            "merchandiseId": "gid://shopify/ProductVariant/<component_variant_id_3>",
            "quantity": 4
          }
        ]
      }
    }
  ]
}
```
I can see the operation in the Run details (under Shopify Partners), but no changes are made to the Cart.  

However, this function output results in the expected behavior in the checkout (Line #0 shows the bundle product's name with the components nested under it):
```
{
  "operations": [
    {
      "expand": {
        "cartLineId": "gid://shopify/CartLine/0",
        "expandedCartItems": [
          {
            "merchandiseId": "gid://shopify/ProductVariant/<component_variant_id_1>",
            "quantity": 3
          },
          {
            "merchandiseId": "gid://shopify/ProductVariant/<component_variant_id_2>",
            "quantity": 1
          },
          {
            "merchandiseId": "gid://shopify/ProductVariant/<component_variant_id_3>",
            "quantity": 4
          }
        ]
      }
    }
  ]
}
```

I am fairly certain both examples were working correctly in the first week of April.</div>

**Comment by ignacio-chiazzo** [comment]
We temporarily disabled multipack bundles until we solve a technical issue. We do plan on supporting multipack bundles in the near future. 

For now, at least one of the components must have quantity 1.

**Comment by gkrauthamer** [comment]
Hi, I'm on a team that works on front-end development and customization for Shopify and I was referred to this issue report by Shopify support. Are there any updates on resolving this issue?

**Comment by siddhantbajaj** [comment]
> For now, at least one of the components must have quantity 1.

We have removed this restriction now. So you can set any quantity to bundle components in the expand operation.
