### ISSUE TITLE
Bundles Cart Transform deploy error - wasm-validator error unexpected false: all used features should be allowed

### ISSUE THREAD

**Issue by tman16** [Shopify/function-examples#255]
`
wasm-validator error in function 1] unexpected false: all used features should be allowed
Fatal: error validating input
error: failed to process wasm at `/Users/tom/Dropbox/Shopify
Apps/product-level-stock/extensions/bundles-cart-transform/target/wasm32-wasi/release/cart_transform.rustc.wasm`

Caused by:
    `wasm-opt` failed to execute

Caused by:
    failed to execute "/Users/tom/Library/Caches/cargo-wasi/0.1.27/wasm-opt/bin/wasm-opt" "/Users/tom/Dropbox/Shopify
Apps/product-level-stock/extensions/bundles-cart-transform/target/wasm32-wasi/release/.tmp9gzg6Z/input.wasm" "-Os" "-o" "/Users/tom/Dropbox/Shopify
Apps/product-level-stock/extensions/bundles-cart-transform/target/wasm32-wasi/release/cart_transform.wasi.wasm" "--enable-bulk-memory" "--debuginfo"
        status: exit status: 1`

**Comment by dekstech** [comment]
I keep getting this same error as well

**Comment by tman16** [comment]
So I have found some information that may be it is because I am using a Mac OS and seems like Mac's can have issues with Rust. Are you using Mac OS also @dekstech

I personally don't want to be using Rust nor learn it just to use bundles - would much prefer a js template instead to work off so if someone is kind enough to help make this happen and convert the current rust one - it would be much appreciated.

**Comment by dekstech** [comment]
@tman16 Yes I’m on macOS

**Comment by dekstech** [comment]
@tman16 i am installing Parallels to confirm; let me know if you have a template / extension with js in it

**Comment by dekstech** [comment]
@tman16 I am getting same issue on windows Parallels boss

**Comment by dekstech** [comment]
@tman16 see above, this fix works!

**Comment by adampetro** [comment]
Happy to hear that this resolved your issue.

> Was this just released?

`cargo-wasi` version `0.1.28` was just released yesterday.
