### ISSUE TITLE
Retrieve custom attributes from Cart / Lines

### ISSUE THREAD

**Issue by julhenry** [Shopify/function-examples#269]
I'm using the StoreFront API to create a checkout and add some lines with custom attributes.
Then with a Discount-order function i'm trying to retrieve a specific key to apply a discount. However, my attributes are always empty.
I wonder if the customAttributes are really sent to my custom function ?
Should i do something with the graphQL query ?

**Comment by daddy88** [comment]
If you not already did the following: You should add the custom attributes to the functions `input.graphql` file, and run the typegen command afterwards.

Here's an example of an attribute named b2b_discount_percent, that can be accessed using `input.cart.b2b_discount_percent.value`:

```graphql
query Input {
  cart {
    b2b_discount_percent: attribute (key: "b2b_discount_percent") {
      value
    }
    lines {
      cost {
        subtotalAmount {
          amount
        }
      }
      quantity
      merchandise {
        __typename
        ...on ProductVariant {
            id
        }
      }
    }
  }
}
```
