### ISSUE TITLE
new Date() always returns 0 unix time (1970-01-01 00:00:00)

### ISSUE THREAD

**Issue by alexsemeniuk-digiscorp** [Shopify/function-examples#301]
I'm trying to get a current date to build a checkout flow with some date-based restrictions. But when I run `new Date()` it always gives me the start of epoch time (1970-01-01 00:00:00).

It does not apply specifically to the examples in this repo, but to Shopify functions in general.
I basically have the following code: 

```js
export default
  (input: InputQuery): FunctionResult => {
    const startTime = new Date("2023-08-03T15:00:00Z");
    const endTime = new Date("2023-08-03T17:00:00Z");
    const now = new Date();

    const errors: FunctionError[] = [];
    const error = {};

    if (now >= startTime && now <= endTime) {
      errors.push(error)
    }

    return { errors };
  };
```

But the `if` body never gets executed. I tried debugging it and discovered that `now` is actually 1970-01-01.

**Comment by nickwesselman** [comment]
Functions are [deterministic](https://shopify.dev/docs/apps/functions#limitations), and thus clock time is not available.

We do have plans to make date/time available via input query. You can follow status of that in [this feature request](https://github.com/Shopify/function-examples/discussions/215).
