### ISSUE TITLE
Cart Transform API bug - customized bundles

### ISSUE THREAD

**Issue by meandillar** [Shopify/function-examples#308]
I've been experimenting with Cart Transform functions and came across some unusual behaviour when using different combinations of Merge and Expand operations and switching between cart and checkout.

Let's say I have 2 bundle configurations:

1. an Expand bundle with the following configuration
Parent ID: `gid://shopify/ProductVariant/111`
Child Component ID:`gid://shopify/ProductVariant/211` (caramel)
Child Component ID: `gid://shopify/ProductVariant/211` (caramel)

2. a Merge bundle
Parent variant ID: `gid://shopify/ProductVariant/111`
Child Component ID: `gid://shopify/ProductVariant/212` (chocolate)
Child Component ID: `gid://shopify/ProductVariant/212` (chocolate)

Things to note: 
- both parents are the same for each bundle
- the child components of both bundles come from the same product but are different flavours
- the parents and children are from different products
- both bundles work when only one configuration or the other is added to metafields

**Behaviour:**
If you add 2 x `gid://shopify/ProductVariant/211` (caramel) to the cart, it shows 1 x `gid://shopify/ProductVariant/111` (parent) in the cart. Upon navigation to checkout it shows the 2 x caramel variants nested, which is correct. 

Navigate back to the store and add 2 x `gid://shopify/ProductVariant/212` (chocolate) and it shows 2 x `gid://shopify/ProductVariant/111` (parent) in the cart. Upon navigation to checkout it shows 4 x `gid://shopify/ProductVariant/212` (chocolate) nested beneath the parent.

**Expected Checkout:**
- A bundle with 2 x `gid://shopify/ProductVariant/212` (chocolate)
- A bundle with 2 x `gid://shopify/ProductVariant/211` (caramel)

I can assume from this behaviour that there is either a bug or there is some kind of limitation where you can't associate multiple bundle configurations with a single variant.

**Comment by horst7000** [comment]
I experience a very similar issue when using the same parentVariant for multiple customized bundles, except I only use merge operations. 

I could see a possible solution where not only the **parentVariantId** but also the **title** gets taken into consideration before merging effectively different bundles together and keep them separate cart items instead.

**Comment by meandillar** [comment]
@horst7000 I've tested using only merge operations targeting the same parent variant with different child component variants and I'm also experiencing bugs.

I'm wondering if the only way around this problem is to create a new parent variant for each bundle possibility. This is not ideal though because when bundling products that have several options/variants we will need to create lots of variants. The ideal scenario for us would be having a single parent variant and being able to select the child component variants from a product selector to attach to that parent dynamically.

**Comment by Ale1234509** [comment]
Any update regarding this one? I'm experiencing the same issues with the merge operation.

**Comment by anthony-v-sundae-lane** [comment]
Confirming we're experiencing the same issue. I flagged this in a recent AMA on Discord and didn't get a response beyond the initial saying its supposed to work (ie, create two bundles, not a single combined bundle)

**Comment by rnovacek** [comment]
Any update on this? This is the biggest blocker for us that prevents us from using native bundles.
