### ISSUE TITLE
Function not found issue

### ISSUE THREAD

**Issue by shubhamtechspawn** [Shopify/function-examples#339]
I am trying to create automatic discount and for that i am using discount function in that i facing below issue
` {"data":{"discountAutomaticAppCreate":{"userErrors":[{"field":["automaticAppDiscount","functionId"],"message":"Function not found."}],"automaticAppDiscount":null}},"extensions":{"cost":{"requestedQueryCost":12,"actualQueryCost":10,"throttleStatus":{"maximumAvailable":1000,"currentlyAvailable":990,"restoreRate":50}}}}`

Here is my code or request 
`` $client = new Graphql($session->getShop(), $session->getAccessToken());
            $query = <<<'QUERY'
            mutation discountAutomaticAppCreate($automaticAppDiscount: DiscountAutomaticAppInput!) {
                discountAutomaticAppCreate(automaticAppDiscount: $automaticAppDiscount) {
                userErrors {
                    field
                    message
                }
                automaticAppDiscount {
                    discountId
                    title
                    startsAt
                    endsAt
                    status
                    appDiscountType {
                    appKey
                    functionId
                    }
                    combinesWith {
                    orderDiscounts
                    productDiscounts
                    shippingDiscounts
                    }
                }
                }
            }
            QUERY;

            $variables = [
                "automaticAppDiscount" => [
                    "title" => "Take 5$ from discount",
                    "functionId" => "9ba565d2-8343-4d10-b9aa-e4abdd167be3",
                    
                    // Combines with other discounts
                    "combinesWith" => [
                        "orderDiscounts" => true,
                        "productDiscounts" => true,
                        "shippingDiscounts" => true,
                    ],
                    
                    // Start and end dates for the discount
                    "startsAt" => "2021-02-02T17:09:21Z",
                    "endsAt" => "2022-02-02T17:09:21Z",
                    
                    // Metafields for additional configuration
                    "metafields" => [
                        [
                            "namespace" => "default",
                            "key" => "function-configuration",
                            "type" => "json",
                            "value" => json_encode([
                                "discounts" => [
                                    [
                                        "value" => [
                                            "fixedAmount" => [
                                                "amount" => 5
                                            ]
                                        ],
                                        "targets" => [
                                            [
                                                "orderSubtotal" => [
                                                    "excludedVariantIds" => []
                                                ]
                                            ]
                                        ]
                                    ]
                                ],
                                "discountApplicationStrategy" => "FIRST"
                            ])
                        ]
                    ],
                ]
            ];
            

            $response = $client->query(["query" => $query, "variables" => $variables]);
` 

Please help me to get resolve this issue.

Thank You
Shubham

**Comment by meandillar** [comment]
Experiencing the same issue. I can successfully create the discount in the GraphiQL app using the functionId from the `.env` file, but receive "Function not found" from within my app. Api key is correct and scopes include `write_discounts`
