### ISSUE TITLE
Delivery renaming not working with Google Pay on Product page

### ISSUE THREAD

**Issue by KTruong008** [Shopify/function-examples#345]
A merchant recently brought to my attention that a delivery method rename customization that works on the checkout page with Google Pay, renaming "Standard 2" to "Free tracked shipping", is not working with Google Pay on the product detail page:

Checkout (working as expected):
![2](https://github.com/Shopify/function-examples/assets/17548405/bec3a2d9-c671-489d-a8b6-c1b47207b107)

Product detail page (not renaming "Standard 2"):
![1](https://github.com/Shopify/function-examples/assets/17548405/e123fa62-45df-4bb7-a4a1-5b63615acfad)

I'm using the `2023-07` API, I'm not sure if I'm missing something on my end. Is this a known limitation, a bug, or something else?

**Comment by nickwesselman** [comment]
Please direct API questions and issues to Partner Support or [Community Forums](https://community.shopify.com/c/shopify-functions/bd-p/functions).
