### ISSUE TITLE
Unable to apply different discounts to different cart items

### ISSUE THREAD

**Issue by vikasanjana9981** [Shopify/function-examples#350]
I am trying to apply different discounts to each cart item by using a meta value of the product using product discount functions but I am not able to.
`
(input) => {
    const targets = input.cart.lines
      // Only include cart lines with a quantity of two or more
      // and a targetable product variant
      .filter(line => {
        const variant = /** @type {ProductVariant} */ (line.merchandise);
        return variant.metafield?.value
      })
      .map(line => {
        const variant = /** @type {ProductVariant} */ (line.merchandise);
        return /** @type {Target} */ ({
          // Use the variant ID to create a discount target
          productVariant: {
            id: variant.id
          }
        });
      });

      // getting particular cart count
      const cartLineCount = input.cart.lines.length;

    if (!targets.length) {
      // You can use STDERR for debug logs in your function
      console.error("No cart lines qualify for volume discount.");
      return EMPTY_DISCOUNT;
    }
   

    // The @shopify/shopify_function package applies JSON.stringify() to your function result
    // and writes it to STDOUT
    if (input?.cart?.buyerIdentity?.customer?.hasTags[0].hasTag) {
      return {
        discounts: [
          {
            // @ts-ignore
            message : `Membership Perk Discount ${input.cart.lines[cartLineCount - 1].merchandise.metafield.value} %`,
            // Apply the discount to the collected targets
            targets,
            // Define a percentage-based discount
            value: {
              percentage: {
                // @ts-ignore
                value: input.cart.lines[cartLineCount - 1].merchandise.metafield.value
              }
            }
          }
        ],
        discountApplicationStrategy: DiscountApplicationStrategy.First
      };
    }else{
      console.error("No cart lines qualify for volume discount.");
      return EMPTY_DISCOUNT;
    }
  };

**Comment by nickwesselman** [comment]
You can upvote and follow [this feature request](https://github.com/Shopify/function-examples/discussions/194).
