### ISSUE TITLE
Volume discount - not working on heroku

### ISSUE THREAD

**Issue by Prismsword** [Shopify/function-examples#375]
I have tested the volume discount hosted locally and all works fine.

Hosted on Heroku the app index page loads and I can generate a product but the volume discount does not appear as an option in the discounts section. It is like the extension is not active.

Is there another step to get the discount extension working?

**Comment by nickwesselman** [comment]
Did you `deploy` and release your app? Is it then installed on the shop?

**Comment by nickwesselman** [comment]
As issues on this repo are intended to support the templates and samples within, I'm going to close this issue. If you need further assistance, please contact Partner Support or utilize the [Community Forums](https://community.shopify.com/c/shopify-functions/bd-p/functions).
