### ISSUE TITLE
metafield variables are not working for shop metafield for cart checkout validation function

### ISSUE THREAD

**Issue by jaspreetAxt** [Shopify/function-examples#377]
I have created metafiled on shop which is working fine. However am unable to pass the variables. 
in RunInput $selectedProducts supposed to send the values but it is not. 

```
query RunInput($selectedProductTags: [String!], $selectedCollectionIds: [ID!]) {
  cart {
    lines {
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          id
          weight
          product {
         
            hasTags(tags: $selectedProductTags) {
              hasTag
              tag
            }
          }
        }
      }
    }
  }
  shop {
    metafield(
      namespace: "$app:my_cart_checkout_shop_namespace"
      key: "my_cart_checkout_shop_key"
    ) {
      value
    }
  }
}
```

As mentioned in the [doc](https://shopify.dev/docs/apps/functions/input-output/variables-queries) that variables need to be declared into the toml file  is already being declared 

```
  [extensions.input.variables]
   namespace: "$app:my_cart_checkout_shop_namespace"
   key: "my_cart_checkout_shop_key"
```

![image](https://github.com/Shopify/function-examples/assets/69665165/f76efb89-c300-4a5e-af5f-7084b5d589df)

**Comment by nickwesselman** [comment]
As specified in the docs, input query variables need to be set on the function owner. Checkout validation doesn't currently expose a function owner on which to set metafields, but this is in their roadmap.

**Comment by nickwesselman** [comment]
Support for this can be tracked [here](https://github.com/Shopify/function-examples/discussions/206).
