### ISSUE TITLE
Update Polaris version in app templates

### ISSUE THREAD

**Issue by wantgoworld** [Shopify/function-examples#419]
## Which template or example
Specify the sample or template, and what flavor/language, if applicable.
order discount

## Describe the bug
clone the event and npm installl 
 Didn't do anything else.
 X [ERROR] No matching export in "node_modules/@shopify/polaris/build/esm/index.js" for import "BlockStack"
## Steps to reproduce
Include the Shopify CLI command to reproduce, if applicable.

## Environment
* Operating system
* Shopify CLI version
@shopify/cli/3.53.0 win32-x64 node-v20.10.0

**Comment by hayesYeSain3** [comment]
+ 1
