### ISSUE TITLE
Multiple Merge Operations Result in Cart Instability

### ISSUE THREAD

**Issue by nelson-maze** [Shopify/function-examples#489]
## Which template or example
CartTransform - Merge Operation

## Describe the bug
Line Item issues begin to occur with any multiple of a CartTransform Merge "bundle" being added to the cart (either by incrementing via form submission on the cart page or via cart AJAX API). Adding any other line items and bundles only exacerbates the issue. 

Partner app dashboard logs indicate that function invocations are occurring where the cart line item inputs are being modified outside of the function's execution, along with potentially extra function invocations being made along the way (accelerating the duplication issues).

### Assumptions
- Latest Dawn theme installed (little to no modifications to it that would impact this)
- You have deployed a Function that uses MergeOperation to implement bundles in-cart
- You have a Function configuration active that can create a bundle in-cart with multiple variants
  - For the purposes of this example, assume the bundle can created from 3 products, with any of their 4 variants each, being valid components of the bundle.
- You have access to your Function's log outputs from the Shopify Partner Dashboard

### Steps

1. Add 1 of each of the component products to the cart to manually create the bundle in-cart.

    - (2/3 bundle products added to cart)
![image](https://github.com/Shopify/function-examples/assets/104597181/249ce8ed-6eb3-4bdd-91ac-300895a9e70a)

    - (3/3 bundle products added to cart)
![image](https://github.com/Shopify/function-examples/assets/104597181/fbbbfd6a-a8f3-448f-99e1-07cb3cf8bebb)

   - Note that this first invocation/interaction properly results in a single bundle being rendered in cart. This is also evident in the partner logs. (3 products input results in 1 Merge Operation with the 3 required component line items in the correct quantities). 
 **FirstBundleInput.json**:  [FirstBundleInput.json](https://github.com/Shopify/function-examples/files/15080630/FirstBundleInput.json)
 **FirstBundleOutput.json**:  [FirstBundleOutput.json](https://github.com/Shopify/function-examples/files/15080635/FirstBundleOutput.json)

2. From the cart page, increment the bundle to 2 via the "+" button. 
    - The page will update and result in:
      - Another line item being added with a price of $0.00 and quantity of 2
      - The first bundle's line item being updated to a quantity of 2 
      ![image](https://github.com/Shopify/function-examples/assets/104597181/0571c18f-9d75-4604-8bdc-b7ab4c3de05e)
      - Note that this is not the theme rendering things incorrectly - the returned response from the Cart AJAX API clearly returns an "empty" bundle line item at $0.00:  [CartResponse_2_Bundles.json](https://github.com/Shopify/function-examples/files/15080966/CartResponse_2_Bundles.json)
      - This is also not the result of incorrect Function output, as the logs correctly display 2 merge operations, each for a group of 3 line items: 
   SecondBundleInput.json: [SecondBundleInput.json](https://github.com/Shopify/function-examples/files/15081008/SecondBundleInput.json)
   SecondBundleOutput.json:  [SecondBundleOutput.json](https://github.com/Shopify/function-examples/files/15081012/SecondBundleOutput.json)
      - Note that the "empty" line item is not found anywhere in the Function input/output logs.

3. Proceed to checkout via the checkout button on the cart page with the current cart of 2 bundles and 2 "empty" bundles.
      - Note that this results in 2 function invocations, each with completely different inputs that seem to indicate line items were further cloned/duplicated between each invocation:
  First Checkout Visit, First Input: [FirstCheckoutVisitInput.json](https://github.com/Shopify/function-examples/files/15081062/FirstCheckoutVisitInput.json)
  First Checkout Visit, First Output: [FirstCheckoutVisitOutput.json](https://github.com/Shopify/function-examples/files/15081064/FirstCheckoutVisitOutput.json)
  First Checkout Visit, Second Input: [FirstCheckoutVisit_SecondInput.json](https://github.com/Shopify/function-examples/files/15081067/FirstCheckoutVisit_SecondInput.json)
  First Checkout Visit, Second Output: [FirstCheckoutVisit_SecondOutput.json](https://github.com/Shopify/function-examples/files/15081069/FirstCheckoutVisit_SecondOutput.json)
  
    - These function invocations with modified inputs result in the cart now being completely different from even the original "2" line items (Cart AJAX API line items JSON found here [CartResponse_FirstDuplicationResponse.json](https://github.com/Shopify/function-examples/files/15081162/CartResponse_FirstDuplicationResponse.json)): 
  ![image](https://github.com/Shopify/function-examples/assets/104597181/6f38028e-9084-4c0c-a664-eadcdb884b60)

     - The expected outputs of the function are still technically correct - but the input varying is what is resulting in this behavior between invocations, not the function execution itself.
     - The only user interaction here between function invocations was the visit to checkout.

4. Navigate back to the cart page, and attempt to "correct" the cart by deleting a line item (any of them)
   - This only results in a continuation of the duplication issues, which after 2 attempts finally results in such a large quantity of line items that the runtime instruction count limit is exceeded, finally resulting in all bundles being broken up, as shown in the cart.
![image](https://github.com/Shopify/function-examples/assets/104597181/9bdc997b-187f-46da-8752-693ad1f696eb)

   - The Function input/output logs of this are below:
     DeleteAttemptInput: [DeleteAttemptInput.json](https://github.com/Shopify/function-examples/files/15081284/DeleteAttemptInput.json)
     DeleteAttemptOutput: [DeleteAttemptOutput.json](https://github.com/Shopify/function-examples/files/15081288/DeleteAttemptOutput.json)

## Expected behavior
* Adding/deleting multiple mergeOperation bundles to the cart should behave the same as adding/deleting multiple "normal" variants to the cart (via form submission or cart AJAX API).  

* Incrementing and decrementing the quantity of mergeOperation bundles should behave the same as with "normal" variants and should increment/decrement the underlying component variants in the cart properly.

* Line items should not duplicate without user interaction and the pricing should be consistent with multiple bundles added to the cart.

* Merge Operations should not result in bug/artifact line items being added to the cart response JSON.

## Environment
* Latest Product Discount Function API for Rust (04/2024) - tested newest RC and unstable. Same situation.
* Latest Version Dawn theme (for frontend testing purposes)
* Latest Shopify CLI
* Shopify Plus Sandbox Store

## Additional context
This is occurring in multiple Shopify Plus environments.

**Comment by nickwesselman** [comment]
Hi @nelson-maze! Please report bugs with Function APIs on [Community](https://community.shopify.com/c/shopify-functions/bd-p/functions). Issues on these OSS repos should be directly related to the code within.

**Comment by nelson-maze** [comment]
Hi Nick - thanks, appreciate the corrected location for this. Issue is
opened there, linking here for posterity:
https://community.shopify.com/c/shopify-functions/carttransform-merge-operations-seem-unstable-with-quantities/td-p/2544569
