### ISSUE TITLE
Code base starting to deviate from template

### ISSUE THREAD

**Issue by stevemar** [Shopify/function-examples#76]
Looking at https://github.com/Shopify/shopify-app-template-node/tree/cli_three/web - there's no longer a backend/frontend directory, just a frontend one. 

We should ensure this code base is kept up to date with https://github.com/Shopify/shopify-app-template-node/ in general.

**Comment by DuncanUszkay1** [comment]
At the moment, each of these custom apps is owned by a separate team. We're yet to come up with a process to ensure that happens- I've assigned this ticket to our project to look into this further.

For now, we will triage any reported issues to the appropriate teams, including issues that result from deviation from the base template.

**Comment by nickwesselman** [comment]
The samples have all been updated since this issue was opened, as they stabilize this should be less of an issue.
