### ISSUE TITLE
Please add AssemblyScript / JavaScript example

### ISSUE THREAD

**Issue by mariusa** [Shopify/function-examples#98]
Hi,

Would you please add a JavaScript example for the discounts, similar to existing Rust example?

Thanks!

**Comment by TheSecurityDev** [comment]
It has to be a language that can be compiled to webassembly.

**Comment by mariusa** [comment]
https://www.wasm.builders/gunjan_0307/compiling-javascript-to-wasm-34lk ? (first google result)

**Comment by rhyek** [comment]
How about https://www.assemblyscript.org/

**Comment by yann120** [comment]
that would be super helpful to have an exemple in AssemblyScript 🙏

**Comment by nickwesselman** [comment]
Currently Rust is our only language with templates and official examples. There are community examples of using AssemblyScript:

- https://github.com/nickwesselman/polyglot-functions/tree/main/extensions/order-discount-assemblyscript
- https://gadget.dev/blog/build-a-shopify-function-using-assemblyscript

We do not have plans at this time to add official examples for AssemblyScript.
